### PR TITLE
Adjust read timeout time to resolve SocketTimeout Exceptions when calling VEP/Ensembl REST service

### PR DESCRIPTION
**Pull request by ao508**
Signed-off-by: Angelica Ochoa <15623749+ao508@users.noreply.github.com>

### CODE REVIEW

**Comment by ao508** [comment]
When you have a moment would you mind taking a look at this PR? @inodb @onursumer 

This adjustment addresses `SocketTimeout Exception`'s we were seeing while reading responses from VEP/ENSEMBL. This exception was observed with every type of VEP/ENSEMBL backend (i.e., locally running VEP, our VEP running on the EC2 machine, and when pointing to public ENSEMBL REST service).

The read timeout here was set to 300 seconds to match the timeout values we set in other areas.

edit: For reference, the default timeout value is 5 seconds

**Comment by onursumer** [comment]
@ao508 These client files are auto generated by [generateApiClientModules.sh](https://github.com/genome-nexus/genome-nexus-java-api-client/blob/master/scripts/generateApiClientModules.sh). So every time we regenerate the files, these changes will be overwritten. If possible we should inject this custom code when we regenerate the clients.

**Comment by onursumer** [comment]
@ao508 An easy (and hacky) solution would be to modify the script and inject the custom code after each line where we see `new OkHttpClient();`. But of course this is not future-proof. If we update the script generator to the latest version something may change on their side and our code injection strategy may no longer be relevant.

**Comment by ao508** [comment]
@onursumer thanks for pointing me to this! I'll see if we can find a solution that will work for us.

**Pull request closed without merging**
